### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by shuvashish76** [BobbyESP/spotdl-android#8]
Hello, would you consider publishing thus app on F-Droid please ?

**Comment by BobbyESP** [comment]
Hi, first of all thank you for the request! This thing really makes me happy :)))

I'll be making an app like Seal (yt-dlp for Android GUI, a very very nice app!) but with this library. The actual app that this library has is just an example of the usage of this library, but it does it's work, download everything from Spotify. No personalization options (like add arguments to the download), that will be in that app.
Thank you!

Now I'll publish an update so stay tuned!

**Comment by BobbyESP** [comment]
Published!

**Comment by BobbyESP** [comment]
To see more about the new app go to [Spowlo](https://github.com/BobbyESP/Spowlo)
