### ISSUE TITLE
Lrc


### ISSUE THREAD

**Issue by venkat2305** [BobbyESP/spotdl-android#9]
Any plans to embed lrc. Synced lyrics

**Comment by BobbyESP** [comment]
Hi! Thanks for asking!

Synced lyrics support is being made in the spotdl library. When the update of the python library is launched, I'll update this library to add that function.

You can follow the progress here: https://github.com/spotDL/spotify-downloader/issues/1589

Info: I'm doing a remake to my Spowlo app for adding this library as it's principal function with a nice UI, custom commands, etc...

**Comment by venkat2305** [comment]
when the spowlo app remake is done. then this app won't be necessary right?

Also, can you suggest a music player ?

**Comment by BobbyESP** [comment]
That's right!

This app is just a sample of the library, not any final downloader app.

I'll make a big effort to bring you and the community a very nice song downloader app!

**Comment by BobbyESP** [comment]
A nice music player could be Retro Music Player (in GitHub - https://github.com/RetroMusicPlayer/RetroMusicPlayer) or Otto Music (Play Store)

**Comment by BobbyESP** [comment]
If the spotDL libraty don't add this by their own, I'll add it on the Spowlo remake

**Comment by venkat2305** [comment]
I've seen a few commits regarding synced lyrics. But, it might take time since it is planned for the next major update i think

**Comment by BobbyESP** [comment]
Yes... So if it isn't implemented soon, I will implement it by myself

**Comment by BobbyESP** [comment]
In the release that I have published in my Telegram channel, t.me/spowlo_chatroom (my Spowlo app), this feature is now availiable

**Comment by venkat2305** [comment]
Lyrics are not synced.

**Comment by BobbyESP** [comment]
You have to select the Synced Lyrics option in the "Experimental features" row

**Comment by BobbyESP** [comment]
![Screenshot_2023-02-16-07-36-14-769_com.bobbyesp.spowlo.png](https://user-images.githubusercontent.com/60316747/219287247-dc687211-3e8e-41d7-82ed-7ce95014a670.png)



https://user-images.githubusercontent.com/60316747/219286947-23f78c9c-c28b-45fb-9084-af6cc3480a0e.mp4

**Comment by venkat2305** [comment]
Getting this error
![Screenshot_2023-02-16-13-19-11-429_com.bobbyesp.spowlo.jpg](https://user-images.githubusercontent.com/55329452/219301147-0966fb34-aba0-4b8e-9f74-834388eac8d5.jpg)

**Comment by BobbyESP** [comment]
@venkat2305 Can you click on the error and send it to me?

**Comment by venkat2305** [comment]
I cleared app data and tried again. It's fixed now

**Comment by venkat2305** [comment]
App version: 1.0.0 (10000)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
spotDL version: Hand-imported v4.0.6

URL: runaway aurora 
Error executing command: [/data/app/~~9TEDEwOxYG4gN8uZtbP2hg==/com.bobbyesp.spowlo-9IryE4qFJzIo_tRBdkPQfQ==/lib/arm64/libpython.bin.so, /data/user/0/com.bobbyesp.spowlo/no_backup/spotdl_android/spotdl/spotdl_bin, download, https://open.spotify.com/track/23rdcrD0Eky4vYn2TZidxJ, --output, /storage/emulated/0/Download/Spowlo, --ytm-data, --lyrics, synced, --bitrate, disable, --format, m4a, --no-cache, --ffmpeg, /data/app/~~9TEDEwOxYG4gN8uZtbP2hg==/com.bobbyesp.spowlo-9IryE4qFJzIo_tRBdkPQfQ==/lib/arm64/libffmpeg.bin.so], exit code: 1, stderr:

**Comment by BobbyESP** [comment]
Try to unselect Use YT metadata. Also open this problem in the Spowlo repo

**Comment by venkat2305** [comment]
Issue persists
App version: 1.0.0 (10000)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
spotDL version: Hand-imported v4.0.6

URL: runaway aurora
Error executing command: [/data/app/~~9TEDEwOxYG4gN8uZtbP2hg==/com.bobbyesp.spowlo-9IryE4qFJzIo_tRBdkPQfQ==/lib/arm64/libpython.bin.so, /data/user/0/com.bobbyesp.spowlo/no_backup/spotdl_android/spotdl/spotdl_bin, download, https://open.spotify.com/track/23rdcrD0Eky4vYn2TZidxJ, --output, /storage/emulated/0/Download/Spowlo, --lyrics, synced, --bitrate, disable, --format, m4a, --no-cache, --ffmpeg, /data/app/~~9TEDEwOxYG4gN8uZtbP2hg==/com.bobbyesp.spowlo-9IryE4qFJzIo_tRBdkPQfQ==/lib/arm64/libffmpeg.bin.so], exit code: 1, stderr:

**Comment by BobbyESP** [comment]
But weired because your app says Hand-imported v4.0.6. can you reinstall the app?

**Comment by BobbyESP** [comment]
Or wait until this weekend's release!
